title: Failed yet successful - Learning from discontinued civic tech initiatives
description: CHI 23' Workshop on Discontinued Civic Tech 
show_downloads: true
google_analytics: G-6MM46DN2JB
theme: jekyll-theme-cayman
plugins:
  - jekyll-remote-theme
