title: Failed yet successful - Learning from discontinued civic tech initiatives
description: Workshop at CHI'23 on April 2023 in Hamburg, Germany
show_downloads: true
google_analytics: G-6MM46DN2JB
theme: jekyll-theme-cayman
plugins:
  - jekyll-remote-theme
